# Generated by Django 6.0.6 on 2026-06-29 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrintSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('generated_count', models.IntegerField(default=0)),
                ('printed_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_print_snapshots',
                'ordering': ['date'],
            },
        ),
    ]
