# Generated by Django 6.0.6 on 2026-06-29 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprintsnapshot',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='users.company'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyprintsnapshot',
            unique_together={('company', 'date')},
        ),
    ]
