# Generated by Django 6.0.6 on 2026-06-29 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('printer_type', models.CharField(choices=[('laser', 'Laser'), ('thermal', 'Thermal'), ('inkjet', 'Inkjet'), ('dot_matrix', 'Dot Matrix')], default='laser', max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy'), ('error', 'Error')], default='offline', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(default=9100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'printers',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('paper_size', models.CharField(choices=[('a4', 'A4'), ('a5', 'A5'), ('4x6', '4x6 inch'), ('2x1', '2x1 inch'), ('custom', 'Custom')], default='a4', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('printing', 'Printing'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('pages', models.IntegerField(default=1)),
                ('error_message', models.TextField(blank=True)),
                ('barcode_format', models.CharField(blank=True, max_length=20)),
                ('product_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'print_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
