# Generated by Django 6.0.6 on 2026-06-29 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('canvas_json', models.JSONField(default=dict)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='label_thumbnails/')),
                ('width', models.IntegerField(default=400)),
                ('height', models.IntegerField(default=200)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'label_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
