from celery import shared_task
from django.utils import timezone
from django.core.files.base import ContentFile
import io
import csv
import pandas as pd
import logging
from .models import ReportExport

logger = logging.getLogger(__name__)

@shared_task
def generate_report_file(report_id: str):
    """Celery task generating report file as PDF/Excel/CSV and updating ReportExport record"""
    try:
        report = ReportExport.objects.get(id=report_id)
        report.status = 'processing'
        report.save(update_fields=['status'])
        
        company = report.company
        report_type = report.report_type
        fmt = report.format
        
        # 1. Fetch relevant data
        data_list = []
        filename = f"{report_type}_report_{timezone.now().strftime('%Y%m%d_%H%M%S')}"
        
        if report_type == 'products':
            from apps.products.models import Product
            qs = Product.objects.filter(company=company)
            for p in qs:
                data_list.append({
                    'Name': p.name,
                    'SKU': p.sku,
                    'Barcode': p.barcode,
                    'Format': p.barcode_format,
                    'Price': float(p.price) if p.price else 0.0,
                    'Category': p.category.name if p.category else '',
                    'Stock': p.stock,
                    'Reserved Stock': p.reserved_stock,
                    'Location': p.location,
                    'Status': p.status,
                    'Created At': p.created_at.strftime('%Y-%m-%d %H:%M:%S'),
                })
        elif report_type == 'inventory':
            from apps.products.models import Product
            qs = Product.objects.filter(company=company)
            for p in qs:
                data_list.append({
                    'Product Name': p.name,
                    'SKU': p.sku,
                    'Barcode': p.barcode,
                    'Current Stock': p.stock,
                    'Reserved': p.reserved_stock,
                    'Available Stock': p.stock - p.reserved_stock,
                    'Stock Threshold': p.low_stock_threshold,
                    'Status': 'Low Stock' if (p.stock <= p.low_stock_threshold and p.stock > 0) else ('Out of Stock' if p.stock == 0 else 'In Stock'),
                    'Location': p.location,
                })
        elif report_type == 'print_jobs':
            from apps.printers.models import PrintJob
            qs = PrintJob.objects.filter(printer__company=company)
            for j in qs:
                data_list.append({
                    'Title': j.title,
                    'Printer': j.printer.name if j.printer else '',
                    'Quantity': j.quantity,
                    'Paper Size': j.paper_size,
                    'Pages': j.pages,
                    'Status': j.status,
                    'Created By': j.created_by.email if j.created_by else '',
                    'Created At': j.created_at.strftime('%Y-%m-%d %H:%M:%S'),
                })
        elif report_type == 'audit':
            from apps.users.models import AuditLog
            qs = AuditLog.objects.filter(user__company=company)
            for l in qs:
                data_list.append({
                    'User': l.user.email if l.user else '',
                    'Action': l.action,
                    'Resource': l.resource,
                    'IP Address': l.ip_address or '',
                    'Timestamp': l.timestamp.strftime('%Y-%m-%d %H:%M:%S'),
                })
        else:
            # Labels activity
            from apps.barcodes.models import Barcode
            qs = Barcode.objects.filter(generated_by__company=company)
            for b in qs:
                data_list.append({
                    'Value': b.value,
                    'Format': b.format,
                    'Generated By': b.generated_by.email if b.generated_by else '',
                    'Product': b.product.name if b.product else '',
                    'Created At': b.created_at.strftime('%Y-%m-%d %H:%M:%S'),
                })

        # 2. Write to buffer
        df = pd.DataFrame(data_list) if data_list else pd.DataFrame([{'No Data': 'No records found'}])
        
        file_buffer = io.BytesIO()
        content_type = ''
        
        if fmt == 'csv':
            csv_str = df.to_csv(index=False)
            file_buffer.write(csv_str.encode('utf-8'))
            file_name = f"{filename}.csv"
            content_type = 'text/csv'
        elif fmt == 'xlsx':
            with pd.ExcelWriter(file_buffer, engine='openpyxl') as writer:
                df.to_excel(writer, index=False, sheet_name='Report')
            file_name = f"{filename}.xlsx"
            content_type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        else:
            # PDF Generation using ReportLab
            from reportlab.lib.pagesizes import letter
            from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib import colors
            
            pdf_buffer = io.BytesIO()
            doc = SimpleDocTemplate(pdf_buffer, pagesize=letter)
            elements = []
            
            styles = getSampleStyleSheet()
            title_style = ParagraphStyle(
                'ReportTitle',
                parent=styles['Heading1'],
                fontSize=18,
                textColor=colors.HexColor('#6366f1'),
                spaceAfter=15
            )
            elements.append(Paragraph(f"{report_type.replace('_', ' ').title()} Report", title_style))
            elements.append(Paragraph(f"Generated on: {timezone.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
            elements.append(Paragraph(f"Company: {company.name}", styles['Normal']))
            elements.append(Spacer(1, 15))
            
            # Simple table layout
            cols = list(df.columns)
            table_data = [cols]
            for _, row in df.head(100).iterrows():  # Cap pdf rows at 100 for size
                table_data.append([str(v) for v in row.values])
                
            t = Table(table_data)
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#4f46e5')),
                ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                ('BOTTOMPADDING', (0,0), (-1,0), 6),
                ('GRID', (0,0), (-1,-1), 0.5, colors.lightgrey),
                ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                ('FONTSIZE', (0,0), (-1,0), 9),
                ('FONTSIZE', (0,1), (-1,-1), 8),
            ]))
            elements.append(t)
            doc.build(elements)
            
            file_buffer.write(pdf_buffer.getvalue())
            file_name = f"{filename}.pdf"
            content_type = 'application/pdf'
            
        file_data = file_buffer.getvalue()
        file_size = len(file_data)
        
        report.file.save(file_name, ContentFile(file_data))
        report.file_size = file_size
        report.status = 'completed'
        report.completed_at = timezone.now()
        report.save(update_fields=['file', 'file_size', 'status', 'completed_at'])
        
        logger.info(f"Report {report_id} completed successfully")
        
    except ReportExport.DoesNotExist:
        logger.error(f"Report export {report_id} not found")
    except Exception as e:
        logger.error(f"Failed to generate report {report_id}: {e}")
        try:
            report = ReportExport.objects.get(id=report_id)
            report.status = 'failed'
            report.error_message = str(e)
            report.save(update_fields=['status', 'error_message'])
        except Exception:
            pass
