# Generated by Django 6.0.6 on 2026-06-29 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('labels', 'Labels Activity'), ('products', 'Product Catalog'), ('inventory', 'Inventory Status'), ('print_jobs', 'Print Jobs History'), ('audit', 'Audit Log Trail')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=15)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_size', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_exports',
                'ordering': ['-created_at'],
            },
        ),
    ]
