# Generated by Django 6.0.6 on 2026-06-29 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500)),
                ('format', models.CharField(choices=[('CODE128', 'CODE 128'), ('CODE39', 'CODE 39'), ('EAN13', 'EAN-13'), ('EAN8', 'EAN-8'), ('UPC', 'UPC-A'), ('QR', 'QR Code'), ('DATAMATRIX', 'Data Matrix'), ('PDF417', 'PDF417')], default='CODE128', max_length=20)),
                ('svg_data', models.TextField(blank=True)),
                ('png_file', models.FileField(blank=True, null=True, upload_to='barcodes/png/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='barcodes/pdf/')),
                ('width', models.FloatField(default=2.0)),
                ('height', models.IntegerField(default=80)),
                ('display_value', models.BooleanField(default=True)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('foreground_color', models.CharField(default='#000000', max_length=7)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'barcodes',
                'ordering': ['-created_at'],
            },
        ),
    ]
